-- 코드를 입력하세요
SELECT c.CAR_ID, c.CAR_TYPE, ROUND(30 * (c.DAILY_FEE * (100-p.DISCOUNT_RATE)/100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS c
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS h ON c.CAR_ID = h.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS p ON c.CAR_TYPE = p.CAR_TYPE
WHERE c.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE > '2022-11-01' AND START_DATE < '2022-11-30'
) AND p.DURATION_TYPE = '30일 이상'
GROUP BY c.CAR_ID
HAVING CAR_TYPE IN ('세단', 'SUV') AND (FEE >= 500000 AND FEE <= 2000000)
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC
